services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark:
    image: apache/spark:3.5.0
    container_name: spark
    user: root
    volumes:
      - ./spark:/opt/spark-apps
    command: >
      /opt/spark/bin/spark-submit
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0
      --jars /opt/spark-apps/postgresql-42.6.0.jar
      /opt/spark-apps/spark_processor.py
    depends_on:
      - kafka
      - postgres
  
  dashboard:
    image: python:3.11-slim
    container_name: dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app
    working_dir: /app
    command: >
      bash -c "pip install streamlit psycopg2-binary pandas plotly sqlalchemy &&
               streamlit run app.py --server.port=8501 --server.address=0.0.0.0"
    depends_on:
      - postgres

  kafka-setup:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-setup
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "/etc/kafka/create-topics.sh"]
    volumes:
      - ./kafka/create-topics.sh:/etc/kafka/create-topics.sh

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpass
      POSTGRES_DB: stockdb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

volumes:
  postgres_data:

  